### ISSUE TITLE
How to prepare self own data for training ASR Model?

### ISSUE THREAD

**Issue by Minxiangliu** [peter-yh-wu/code_mix_ce#1]
Hi,
I want to use my own data to train the ASR Model, are there any rules for collecting audio files and text files?
I am very confused about [this text file](https://catalog.ldc.upenn.edu/LDC2015S04). Do I need to add some prefixes and paragraphs to this text content?

**Comment by peter-yh-wu** [comment]
Feel free to format your dataset based on the way we did it in e.g. [SEAME](https://github.com/peter-yh-wu/code_mix/tree/4fa30a1a990e0505cf3d7a61b5edcf41ff069577/tasks/SEAME). If you're just getting started with ASR, it may be easier to build on top of a more structured repository like [ESPnet](https://github.com/espnet/espnet).
